#!/bin/bash

clear

service_name=senti-databroker-merge.service
service_dir=/etc/systemd/system
server_dir=/srv/nodejs/senti/services/databroker/merge

service=$service_dir/$service_name

echo Registering Senti Data Broker service for merge ...


if [ ! -e "$service" ]; then
	echo
    echo "Senti Data Broker service is not installed"
	echo "Installing Senti Data Broker service ..."
	sudo cp $server_dir/$service_name $service_dir/$service_name
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl start $service_name
else
    echo "Senti Data Broker service is already installed"
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl stop $service_name
	sudo systemctl start $service_name
fi
